---
- name: Install mandatory packages centos
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: Install docker CE repo
  yum_repository:
    name: docker
    description: docker CE repository
    state: present
    baseurl: "{{ rpm_repo }}"
- name: Install docker CE
  yum: 
    name: docker-ce 
    state: present
