---
- name: Install mandatory packages centos
  yum:
    name: ['epel-release', 'yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: present
- name: Add Docker repo
  get_url:
    url: "{{ rpm_repo }}"
    dest: /etc/yum.repos.d/docer-ce.repo
- name: Install docker CE
  yum:
    name: docker-ce
    state: present
