---
- name: Install mandatory packages centos
  dnf:
    name: ['dnf-plugins-core', 'python-dnf', 'python2']
    state: present
- name: Install docker CE repo
  shell: 'dnf config-manager --add-repo {{ rpm_repo }}'
  args:
    executable: /bin/bash
- name: Install docker CE
  dnf:
    name: docker-ce
    state: present
